app:
  test: 777
  bot:
    token: 6089957461:AAEoYQEna7LrM9iYMkDetsJu-9FSRm9rEVI
  client:
    url: http://localhost:8080/api

server:
  port: 5432

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui